### ISSUE TITLE
Encasing Ice breaks despite of using Silk Touch

### ISSUE THREAD

**Issue by nco2k** [MincraftEinstein/JustMoreCakes#11]
Encasing Ice shouldnt break when using Silk Touch.

**Comment by MincraftEinstein** [comment]
If I remember my initial reason correctly, it wasn't supposed to because it was meant to be an environment block like Frosted Ice from Frost Walker.

**Comment by nco2k** [comment]
ok now i kinda get what the purpose of this block is. i thought it had something to do with storing a cake inside.

but honestly, i dont see how this (and the freezing potions) fit into a cake mod. imho you should remove them altogether and put them in a separate mod.

**Comment by MincraftEinstein** [comment]
The Cake Stand holds cakes, the freezing effect is given by the Frozen Cake, but perhaps I should just move it
