### ISSUE TITLE
JMC breaks the composter

### ISSUE THREAD

**Issue by cyyynthia** [MincraftEinstein/JustMoreCakes#16]
With Just More Cakes! installed, right-clicking on a vanilla composter with an empty hand will cause the composter to get filled. Right clicking on a composter should not have any effect with an empty hand.

Minecraft 1.20.1, Forge 47.2.20, JMC 1.17.3

**Comment by cyyynthia** [comment]
It's me again 👻

Thanks a lot for the very quick fix; is there a chance we can get a patched release in the near future? I'd really love for this bug to be fixed on my server 😅

If it's too annoying for you I could just build it myself and use the latest jar, I feel like it'd be nice to have this fixed in the mod itself

**Comment by MincraftEinstein** [comment]
oh, yeah, sorry, kinda forgot while working on the next major update. I'll try to have it released today or tomorrow
