### ISSUE TITLE
Potion Of Bouncing + Recipe Conflicts

### ISSUE THREAD

**Issue by Yosomii** [MincraftEinstein/JustMoreCakes#19]
Unusual behavior where any vanilla potion can be brewed into Potion Of Bouncing+, and modded brewing recipes that use redstone are overwritten with Potion Of Bouncing +

*The + is for extended time, in this case we're talking about "Potion Of Bouncing (4:00)"

Running with 1.20.1 Forge 47.3.0, Just More Cakes! 1.18.0

**How to replicate:**
1) Brew any potion that does not take redstone (i.e. mundane or thick potions, potions that are already upgraded with extended time or strength, ect.)
2) Add redstone.

**Expected:**
- Nothing (with modding exceptions).

**Observed:**
- Potion is brewed into Potion of Bouncing + (often overwrites modded potions that use redstone in their recipes as well).

**Comment by MincraftEinstein** [comment]
Thank you for reporting this. I will be releasing the fix soon
