### ISSUE TITLE
Fabric 1.21 doesnt work

### ISSUE THREAD

**Issue by Yo-Snowpro** [MincraftEinstein/JustMoreCakes#20]
When I try and boot up my modpack, it just says that it needs to be compatible with fabric loader

**Comment by Yo-Snowpro** [comment]
Heres the error message if you need it:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Just More Cakes!' (jmc) 1.19.0 with any version that is compatible with:
		 - fabricloader 0.15.11
More details:
	 - Mod 'Just More Cakes!' (jmc) 1.19.0 requires version 0.16.0 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.11!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MincraftEinstein** [comment]
Hi. The crash report (error message) says you are using fabric version 0.15.11 but the mod needs at least version 0.16.0. I plan to do another release in a few days to fix a bug. I can try to lower the minimum required version to 0.15.11

**Comment by Yo-Snowpro** [comment]
Sounds good!
