### ISSUE TITLE
Crash with applecore

### ISSUE THREAD

**Issue by smiglssss** [MincraftEinstein/JustMoreCakes#23]
Crashes when trying to eat cake, attempting to open world after crash makes game freeze.
JustMoreCakes-2.0_MC1.12.2
https://mclo.gs/SOhwViG

**Comment by MincraftEinstein** [comment]
Sorry, but I can't help you, this repository didn't even exist when that version was created, and modding and Minecraft have changed a lot since then.

Are you sure it was JMC? I don't think I did anything that would cause that would cause this
