### ISSUE TITLE
Incompatibility with Tinted

### ISSUE THREAD

**Issue by Satrapie** [MincraftEinstein/JustMoreCakes#3]
It seems that when another mod ([Tinted](https://www.curseforge.com/minecraft/mc-mods/tinted)) adds new dye colors, Just More Cakes looks for the new candles variants in the vanilla namespace instead of the Tinted one. Since they don't exist, the game crashes.

[crash-2022-11-11_06.55.41-client.txt](https://github.com/MincraftEinstein/JustMoreCakes/files/9987050/crash-2022-11-11_06.55.41-client.txt)

(However, the problem may lie with the method Tinted uses to save its new colors, I don't know how it works)

**Comment by MincraftEinstein** [comment]
Hello. Thanks for reporting this. After some experimenting and looking at released code and currently unreleased code it would seem that I unknowingly already fixed this and just need to release it to curseforge. It also seems that I unknowingly added support for Tinted with the way JustMoreCakes is set up and just need to create the assets and data to finish making everything look and work right
