### ISSUE TITLE
Stackables compatibility

### ISSUE THREAD

**Issue by nco2k** [MincraftEinstein/JustMoreCakes#9]
any chance you could make your mod compatible with [Stackables](https://modrinth.com/mod/stackables)? i would like to change the Cream Cheese stack size from 16 to 64.

**Comment by MincraftEinstein** [comment]
maybe. I may just change the default stack size instead

**Comment by nco2k** [comment]
idk. the stack size of 16 makes sense for ingredients, but it sucks for people who use mods like Stackables. i think the best solution would be if the creator of Stackables allowed other mod creators to add their own content to the list.

**Comment by theendercore** [comment]
> Tags
> As of version 2.0.0, Stackables functions via tags! Every max stack size is now controlled exclusively through the new tags. If you come across mods that add items you feel should be included in a particular category, you can add them to the appropriate tag with a data pack!
From : https://modrinth.com/mod/stackables

Because that this issue can be closed now. :)
